# Generated by Django 2.2.5 on 2019-09-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_week', models.CharField(max_length=255, verbose_name='Hafta')),
                ('gk', models.CharField(max_length=255, verbose_name='Kaleci')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Teams')),
            ],
            options={
                'verbose_name_plural': 'İlk 11',
            },
        ),
    ]
