# Generated by Django 2.2.5 on 2019-09-11 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_squad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Oyuncu İsmi')),
                ('position', models.CharField(max_length=255, verbose_name='Mevki')),
                ('apps', models.IntegerField(verbose_name='Oynadığı Maç Sayısı')),
                ('starts', models.IntegerField(verbose_name="İlk 11'de Başladığı")),
                ('subs', models.IntegerField(verbose_name='Yedekten girdiği')),
                ('mins', models.CharField(max_length=255, verbose_name='Oynadığı Dakika')),
                ('goals', models.IntegerField(verbose_name='Attığı Gol')),
                ('asst', models.IntegerField(verbose_name='Asist')),
            ],
            options={
                'verbose_name': 'Oyuncu',
                'verbose_name_plural': 'Oyuncular',
            },
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name': 'Takım İsmi', 'verbose_name_plural': 'Takım İsimleri'},
        ),
        migrations.DeleteModel(
            name='Squad',
        ),
        migrations.AddField(
            model_name='players',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Teams'),
        ),
    ]
