# Generated by Django 2.2.5 on 2019-09-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190911_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='apps',
            field=models.IntegerField(blank=True, null=True, verbose_name='Oynadığı Maç Sayısı'),
        ),
        migrations.AlterField(
            model_name='players',
            name='asst',
            field=models.IntegerField(blank=True, null=True, verbose_name='Asist'),
        ),
        migrations.AlterField(
            model_name='players',
            name='goals',
            field=models.IntegerField(blank=True, null=True, verbose_name='Attığı Gol'),
        ),
        migrations.AlterField(
            model_name='players',
            name='mins',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Oynadığı Dakika'),
        ),
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Oyuncu İsmi'),
        ),
        migrations.AlterField(
            model_name='players',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mevki'),
        ),
        migrations.AlterField(
            model_name='players',
            name='starts',
            field=models.IntegerField(blank=True, null=True, verbose_name="İlk 11'de Başladığı"),
        ),
        migrations.AlterField(
            model_name='players',
            name='subs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Yedekten girdiği'),
        ),
    ]
