# Generated by Django 2.2.5 on 2019-09-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190911_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Oyuncu İsmi'),
        ),
    ]
