# Generated by Django 2.2.5 on 2019-09-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190911_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Maç Haftası')),
            ],
            options={
                'verbose_name': 'Hafta',
                'verbose_name_plural': 'Haftalar',
            },
        ),
    ]
