# Generated by Django 2.2.5 on 2019-09-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_matchweek'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchWeek',
        ),
    ]
