# Generated by Django 2.2.5 on 2019-09-13 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_matchweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Squads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=255, verbose_name='Hafta')),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='home.Players', verbose_name='1. Oyuncu')),
                ('p10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p10', to='home.Players', verbose_name='10. Oyuncu')),
                ('p11', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p11', to='home.Players', verbose_name='11. Oyuncu')),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='home.Players', verbose_name='2. Oyuncu')),
                ('p3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p3', to='home.Players', verbose_name='3. Oyuncu')),
                ('p4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p4', to='home.Players', verbose_name='4. Oyuncu')),
                ('p5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p5', to='home.Players', verbose_name='5. Oyuncu')),
                ('p6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p6', to='home.Players', verbose_name='6. Oyuncu')),
                ('p7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p7', to='home.Players', verbose_name='7. Oyuncu')),
                ('p8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p8', to='home.Players', verbose_name='8. Oyuncu')),
                ('p9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p9', to='home.Players', verbose_name='9. Oyuncu')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Teams', verbose_name='Takım')),
            ],
            options={
                'verbose_name': 'İlk 11',
                'verbose_name_plural': "İlk 11'ler",
            },
        ),
    ]
