# Generated by Django 2.2.5 on 2019-09-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_squads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squads',
            name='p1',
            field=models.CharField(max_length=255, verbose_name='1. Oyuncu'),
        ),
        migrations.AlterField(
            model_name='squads',
            name='p10',
            field=models.CharField(max_length=255, verbose_name='10. Oyuncu'),
        ),
        migrations.AlterField(
            model_name='squads',
            name='p11',
            field=models.CharField(max_length=255, verbose_name='11. Oyuncu'),
        ),
        migrations.AlterField(
            model_name='squads',
            name='p2',
            field=models.CharField(max_length=255, verbose_name='2. Oyuncu'),
        ),
        migrations.AlterField(
            model_name='squads',
            name='p3',
            field=models.CharField(max_length=255, verbose_name='3. Oyuncu'),
        ),
        migrations.AlterField(
            model_name='squads',
            name='p4',
            field=models.CharField(max_length=255, verbose_name='4. Oyuncu'),
        ),
        migrations.AlterField(
            model_name='squads',
            name='p5',
            field=models.CharField(max_length=255, verbose_name='5. Oyuncu'),
        ),
        migrations.AlterField(
            model_name='squads',
            name='p6',
            field=models.CharField(max_length=255, verbose_name='6. Oyuncu'),
        ),
        migrations.AlterField(
            model_name='squads',
            name='p7',
            field=models.CharField(max_length=255, verbose_name='7. Oyuncu'),
        ),
        migrations.AlterField(
            model_name='squads',
            name='p8',
            field=models.CharField(max_length=255, verbose_name='8. Oyuncu'),
        ),
        migrations.AlterField(
            model_name='squads',
            name='p9',
            field=models.CharField(max_length=255, verbose_name='9. Oyuncu'),
        ),
    ]
