# Generated by Django 2.2.2 on 2019-10-01 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190913_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Lig İsmi')),
            ],
            options={
                'verbose_name': 'Lig',
                'verbose_name_plural': 'Ligler',
            },
        ),
        migrations.AddField(
            model_name='teams',
            name='league',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.Leagues', verbose_name='Lig'),
        ),
    ]
