# Generated by Django 2.2.2 on 2019-10-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20191001_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Takım Karakter Özelliği')),
            ],
        ),
    ]
