# Generated by Django 2.2.2 on 2019-10-04 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_teamcharacteristic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamcharacteristic',
            options={'verbose_name': 'Takım oyun stili', 'verbose_name_plural': 'Takımların oyun stilleri'},
        ),
        migrations.RemoveField(
            model_name='teamcharacteristic',
            name='name',
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='defans1',
            field=models.BooleanField(blank=True, null=True, verbose_name='Çok değişmeyen ilk onbir'),
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='defans2',
            field=models.BooleanField(blank=True, null=True, verbose_name='Oyunu kendi sahasına yığar'),
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='defans3',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agresif değil'),
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='defans4',
            field=models.BooleanField(blank=True, null=True, verbose_name='Rakip takımın agresif oynamasına sebep olur'),
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='defans5',
            field=models.BooleanField(blank=True, null=True, verbose_name='Rotasyon yapar'),
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='defans6',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ofsayt taktiği oynar'),
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='defans7',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agresif'),
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='power1',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sık ara pas dener'),
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='power10',
            field=models.BooleanField(blank=True, null=True, verbose_name='Kısa pas'),
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='power11',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ortadan saldırır'),
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='power12',
            field=models.BooleanField(blank=True, null=True, verbose_name='Uzaktan şutlar çeker'),
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='power2',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sagdan saldırır'),
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='power3',
            field=models.BooleanField(blank=True, null=True, verbose_name='Soldan saldırır'),
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='power4',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sahaya yayılarak oynar'),
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='power5',
            field=models.BooleanField(blank=True, null=True, verbose_name='Uzun top'),
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='power6',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sık orta açmayı dener'),
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='power7',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sık şut çeker'),
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='power8',
            field=models.BooleanField(blank=True, null=True, verbose_name='Oyunu rakip sahaya yıkar'),
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='power9',
            field=models.BooleanField(blank=True, null=True, verbose_name='Topa daha çok sahip olur'),
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.Teams', verbose_name='Takım'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TeamPowerUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power1', models.IntegerField(verbose_name='Gol şanslarındaki bitiricilik')),
                ('power2', models.IntegerField(verbose_name='Ara toplardan pozisyon yaratma')),
                ('power3', models.IntegerField(verbose_name='Bireysel yeteneklerden pozisyon yaratma')),
                ('power4', models.IntegerField(verbose_name='Yenilir pozisyondan geri dönmek')),
                ('power5', models.IntegerField(verbose_name='Gol pozisyonlarına girme')),
                ('power6', models.IntegerField(verbose_name='Frikiklerden şut çekme')),
                ('power7', models.IntegerField(verbose_name='Ceza sahası dışından şut şansı yaratma')),
                ('power8', models.IntegerField(verbose_name='Duran toplardan saldırma')),
                ('power9', models.IntegerField(verbose_name='Kanatlardan saldırma')),
                ('power10', models.IntegerField(verbose_name='Kontra ataklar')),
                ('power11', models.IntegerField(verbose_name='Ofsayttan kaçınma')),
                ('power12', models.IntegerField(verbose_name='Topa sahip olma')),
                ('defans1', models.IntegerField(verbose_name='Duran topları savunma')),
                ('defans2', models.IntegerField(verbose_name='Hava topu mücadelesi')),
                ('defans3', models.IntegerField(verbose_name='Bireysel hatalardan kaçınma')),
                ('defans4', models.IntegerField(verbose_name='Karşı takıma çok pozisyon vermeme')),
                ('defans5', models.IntegerField(verbose_name='Rakipten top çalma')),
                ('defans6', models.IntegerField(verbose_name='Ceza sahası dışından şut çektirmeme')),
                ('defans7', models.IntegerField(verbose_name='Ara paslara karşı savunma')),
                ('defans8', models.IntegerField(verbose_name='Tehlikeli noktalarda faul yapmaktan kaçınma')),
                ('defans9', models.IntegerField(verbose_name='Galip durumdan kaybetmeme')),
                ('defans10', models.IntegerField(verbose_name='Kontra atakları savunma')),
                ('defans11', models.IntegerField(verbose_name='Kanatlardan saldırılara karşı savunma')),
                ('defans12', models.IntegerField(verbose_name='Yetenekli oyunculara karşı savunma')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Teams', verbose_name='Takım')),
            ],
            options={
                'verbose_name': 'Takımın Güçlü-Zayıf Yönleri',
                'verbose_name_plural': 'Takımların Güçlü-Zayıf Yönleri',
            },
        ),
    ]
