# Generated by Django 2.2.2 on 2019-10-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20191004_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampowerup',
            name='defans1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duran topları savunma'),
        ),
        migrations.AlterField(
            model_name='teampowerup',
            name='defans10',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kontra atakları savunma'),
        ),
        migrations.AlterField(
            model_name='teampowerup',
            name='defans11',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kanatlardan saldırılara karşı savunma'),
        ),
        migrations.AlterField(
            model_name='teampowerup',
            name='defans12',
            field=models.IntegerField(blank=True, null=True, verbose_name='Yetenekli oyunculara karşı savunma'),
        ),
        migrations.AlterField(
            model_name='teampowerup',
            name='defans2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hava topu mücadelesi'),
        ),
        migrations.AlterField(
            model_name='teampowerup',
            name='defans3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bireysel hatalardan kaçınma'),
        ),
        migrations.AlterField(
            model_name='teampowerup',
            name='defans4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Karşı takıma çok pozisyon vermeme'),
        ),
        migrations.AlterField(
            model_name='teampowerup',
            name='defans5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rakipten top çalma'),
        ),
        migrations.AlterField(
            model_name='teampowerup',
            name='defans6',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ceza sahası dışından şut çektirmeme'),
        ),
        migrations.AlterField(
            model_name='teampowerup',
            name='defans7',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ara paslara karşı savunma'),
        ),
        migrations.AlterField(
            model_name='teampowerup',
            name='defans8',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tehlikeli noktalarda faul yapmaktan kaçınma'),
        ),
        migrations.AlterField(
            model_name='teampowerup',
            name='defans9',
            field=models.IntegerField(blank=True, null=True, verbose_name='Galip durumdan kaybetmeme'),
        ),
        migrations.AlterField(
            model_name='teampowerup',
            name='power1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gol şanslarındaki bitiricilik'),
        ),
        migrations.AlterField(
            model_name='teampowerup',
            name='power10',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kontra ataklar'),
        ),
        migrations.AlterField(
            model_name='teampowerup',
            name='power11',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ofsayttan kaçınma'),
        ),
        migrations.AlterField(
            model_name='teampowerup',
            name='power12',
            field=models.IntegerField(blank=True, null=True, verbose_name='Topa sahip olma'),
        ),
        migrations.AlterField(
            model_name='teampowerup',
            name='power2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ara toplardan pozisyon yaratma'),
        ),
        migrations.AlterField(
            model_name='teampowerup',
            name='power3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bireysel yeteneklerden pozisyon yaratma'),
        ),
        migrations.AlterField(
            model_name='teampowerup',
            name='power4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Yenilir pozisyondan geri dönmek'),
        ),
        migrations.AlterField(
            model_name='teampowerup',
            name='power5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gol pozisyonlarına girme'),
        ),
        migrations.AlterField(
            model_name='teampowerup',
            name='power6',
            field=models.IntegerField(blank=True, null=True, verbose_name='Frikiklerden şut çekme'),
        ),
        migrations.AlterField(
            model_name='teampowerup',
            name='power7',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ceza sahası dışından şut şansı yaratma'),
        ),
        migrations.AlterField(
            model_name='teampowerup',
            name='power8',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duran toplardan saldırma'),
        ),
        migrations.AlterField(
            model_name='teampowerup',
            name='power9',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kanatlardan saldırma'),
        ),
    ]
