# Generated by Django 2.2.2 on 2019-10-05 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20191004_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPowerUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power1', models.IntegerField(verbose_name='Bitiricilik')),
                ('power2', models.IntegerField(verbose_name='Uzaktan şutlar')),
                ('power3', models.IntegerField(verbose_name='Ara pas verme')),
                ('power4', models.IntegerField(verbose_name='Top tutma')),
                ('power5', models.IntegerField(verbose_name='Hava topu')),
                ('power6', models.IntegerField(verbose_name='Kilit pas verme')),
                ('power7', models.IntegerField(verbose_name='Duran top kullanma')),
                ('power8', models.IntegerField(verbose_name='Direkt free kick')),
                ('power9', models.IntegerField(verbose_name='Pas verme')),
                ('power10', models.IntegerField(verbose_name='Orta açma')),
                ('power11', models.IntegerField(verbose_name='Ofsayt farkındalığı')),
                ('power12', models.IntegerField(verbose_name='Adam geçme')),
                ('power13', models.IntegerField(verbose_name='Kafayla şutlar')),
                ('defans1', models.IntegerField(verbose_name='Defansif katkı')),
                ('defans2', models.IntegerField(verbose_name='Top kapma')),
                ('defans3', models.IntegerField(verbose_name='Disiplin')),
                ('defans4', models.IntegerField(verbose_name='Konsantrasyon')),
                ('defans5', models.IntegerField(verbose_name='Penaltı kurtarma')),
                ('defans6', models.IntegerField(verbose_name='Şut durdurma refleksleri')),
                ('defans7', models.IntegerField(verbose_name='Şut engelleme')),
                ('defans8', models.IntegerField(verbose_name='Uzaktan şutları kurtarma')),
                ('defans9', models.IntegerField(verbose_name='Kısa mesafe şutlarını kurtarma')),
                ('defans10', models.IntegerField(verbose_name='Yan toplar')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Players', verbose_name='Oyuncu')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Teams', verbose_name='Takımı')),
            ],
            options={
                'verbose_name': 'Oyuncunun güçlü-zayıf yönleri',
                'verbose_name_plural': 'Oyuncuların güçlü-zayıf yönleri',
            },
        ),
    ]
