# Generated by Django 2.2.2 on 2019-10-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_playerpowerup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerpowerup',
            name='team',
        ),
    ]
