# Generated by Django 2.2.2 on 2019-10-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_playerpowerup_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerpowerup',
            name='defans1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Defansif katkı'),
        ),
        migrations.AlterField(
            model_name='playerpowerup',
            name='defans10',
            field=models.IntegerField(blank=True, null=True, verbose_name='Yan toplar'),
        ),
        migrations.AlterField(
            model_name='playerpowerup',
            name='defans2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Top kapma'),
        ),
        migrations.AlterField(
            model_name='playerpowerup',
            name='defans3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Disiplin'),
        ),
        migrations.AlterField(
            model_name='playerpowerup',
            name='defans4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Konsantrasyon'),
        ),
        migrations.AlterField(
            model_name='playerpowerup',
            name='defans5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Penaltı kurtarma'),
        ),
        migrations.AlterField(
            model_name='playerpowerup',
            name='defans6',
            field=models.IntegerField(blank=True, null=True, verbose_name='Şut durdurma refleksleri'),
        ),
        migrations.AlterField(
            model_name='playerpowerup',
            name='defans7',
            field=models.IntegerField(blank=True, null=True, verbose_name='Şut engelleme'),
        ),
        migrations.AlterField(
            model_name='playerpowerup',
            name='defans8',
            field=models.IntegerField(blank=True, null=True, verbose_name='Uzaktan şutları kurtarma'),
        ),
        migrations.AlterField(
            model_name='playerpowerup',
            name='defans9',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kısa mesafe şutlarını kurtarma'),
        ),
        migrations.AlterField(
            model_name='playerpowerup',
            name='power1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bitiricilik'),
        ),
        migrations.AlterField(
            model_name='playerpowerup',
            name='power10',
            field=models.IntegerField(blank=True, null=True, verbose_name='Orta açma'),
        ),
        migrations.AlterField(
            model_name='playerpowerup',
            name='power11',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ofsayt farkındalığı'),
        ),
        migrations.AlterField(
            model_name='playerpowerup',
            name='power12',
            field=models.IntegerField(blank=True, null=True, verbose_name='Adam geçme'),
        ),
        migrations.AlterField(
            model_name='playerpowerup',
            name='power13',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kafayla şutlar'),
        ),
        migrations.AlterField(
            model_name='playerpowerup',
            name='power2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Uzaktan şutlar'),
        ),
        migrations.AlterField(
            model_name='playerpowerup',
            name='power3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ara pas verme'),
        ),
        migrations.AlterField(
            model_name='playerpowerup',
            name='power4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Top tutma'),
        ),
        migrations.AlterField(
            model_name='playerpowerup',
            name='power5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hava topu'),
        ),
        migrations.AlterField(
            model_name='playerpowerup',
            name='power6',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilit pas verme'),
        ),
        migrations.AlterField(
            model_name='playerpowerup',
            name='power7',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duran top kullanma'),
        ),
        migrations.AlterField(
            model_name='playerpowerup',
            name='power8',
            field=models.IntegerField(blank=True, null=True, verbose_name='Direkt free kick'),
        ),
        migrations.AlterField(
            model_name='playerpowerup',
            name='power9',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pas verme'),
        ),
    ]
