# Generated by Django 2.2.2 on 2019-10-16 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20191005_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamcharacteristic',
            options={'verbose_name': 'Oyuncu oyun stili', 'verbose_name_plural': 'Oyuncuların oyun stilleri'},
        ),
        migrations.RemoveField(
            model_name='teamcharacteristic',
            name='defans6',
        ),
        migrations.RemoveField(
            model_name='teamcharacteristic',
            name='defans7',
        ),
        migrations.RemoveField(
            model_name='teamcharacteristic',
            name='team',
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='Player',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.Players', verbose_name='Oyuncu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='defans1',
            field=models.BooleanField(blank=True, null=True, verbose_name='Top çalmaya çalışmaz'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='defans2',
            field=models.BooleanField(blank=True, null=True, verbose_name='Top çalmayı sever'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='defans3',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sık faul yapar'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='defans4',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sık topu defanstan uzaklaştırır'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='defans5',
            field=models.BooleanField(blank=True, null=True, verbose_name='Topu yumruklamayı sever'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power1',
            field=models.BooleanField(blank=True, null=True, verbose_name='Koşu yoluna pas atmayı sever'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power10',
            field=models.BooleanField(blank=True, null=True, verbose_name='Uzun top oynamayı sever'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power11',
            field=models.BooleanField(blank=True, null=True, verbose_name='Orta açmayı sever'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power12',
            field=models.BooleanField(blank=True, null=True, verbose_name='Top indirmeyi sever'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power2',
            field=models.BooleanField(blank=True, null=True, verbose_name='Kanattan içeri girmeyi sever'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power3',
            field=models.BooleanField(blank=True, null=True, verbose_name='Endirek duran topta tehlike'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power4',
            field=models.BooleanField(blank=True, null=True, verbose_name='Uzaktan şut çekmeyi sever'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power5',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sık faul alır'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power6',
            field=models.BooleanField(blank=True, null=True, verbose_name='Adam geçmeyi sever'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power7',
            field=models.BooleanField(blank=True, null=True, verbose_name='Kontra atak tehditi'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power8',
            field=models.BooleanField(blank=True, null=True, verbose_name='Kısa pas vermeyi sever'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power9',
            field=models.BooleanField(blank=True, null=True, verbose_name='Topu havalandırmayı sever'),
        ),
    ]
