# Generated by Django 2.2.2 on 2019-10-16 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20191016_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamcharacteristic',
            options={'verbose_name': 'Takım oyun stili', 'verbose_name_plural': 'Takımların oyun stilleri'},
        ),
        migrations.RemoveField(
            model_name='teamcharacteristic',
            name='Player',
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='defans6',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ofsayt taktiği oynar'),
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='defans7',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agresif'),
        ),
        migrations.AddField(
            model_name='teamcharacteristic',
            name='team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.Teams', verbose_name='Takım'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='defans1',
            field=models.BooleanField(blank=True, null=True, verbose_name='Çok değişmeyen ilk onbir'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='defans2',
            field=models.BooleanField(blank=True, null=True, verbose_name='Oyunu kendi sahasına yığar'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='defans3',
            field=models.BooleanField(blank=True, null=True, verbose_name='Agresif değil'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='defans4',
            field=models.BooleanField(blank=True, null=True, verbose_name='Rakip takımın agresif oynamasına sebep olur'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='defans5',
            field=models.BooleanField(blank=True, null=True, verbose_name='Rotasyon yapar'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power1',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sık ara pas dener'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power10',
            field=models.BooleanField(blank=True, null=True, verbose_name='Kısa pas'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power11',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ortadan saldırır'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power12',
            field=models.BooleanField(blank=True, null=True, verbose_name='Uzaktan şutlar çeker'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power2',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sagdan saldırır'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power3',
            field=models.BooleanField(blank=True, null=True, verbose_name='Soldan saldırır'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power4',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sahaya yayılarak oynar'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power5',
            field=models.BooleanField(blank=True, null=True, verbose_name='Uzun top'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power6',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sık orta açmayı dener'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power7',
            field=models.BooleanField(blank=True, null=True, verbose_name='Sık şut çeker'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power8',
            field=models.BooleanField(blank=True, null=True, verbose_name='Oyunu rakip sahaya yıkar'),
        ),
        migrations.AlterField(
            model_name='teamcharacteristic',
            name='power9',
            field=models.BooleanField(blank=True, null=True, verbose_name='Topa daha çok sahip olur'),
        ),
        migrations.CreateModel(
            name='PlayerCharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power1', models.BooleanField(blank=True, null=True, verbose_name='Koşu yoluna pas atmayı sever')),
                ('power2', models.BooleanField(blank=True, null=True, verbose_name='Kanattan içeri girmeyi sever')),
                ('power3', models.BooleanField(blank=True, null=True, verbose_name='Endirek duran topta tehlike')),
                ('power4', models.BooleanField(blank=True, null=True, verbose_name='Uzaktan şut çekmeyi sever')),
                ('power5', models.BooleanField(blank=True, null=True, verbose_name='Sık faul alır')),
                ('power6', models.BooleanField(blank=True, null=True, verbose_name='Adam geçmeyi sever')),
                ('power7', models.BooleanField(blank=True, null=True, verbose_name='Kontra atak tehditi')),
                ('power8', models.BooleanField(blank=True, null=True, verbose_name='Kısa pas vermeyi sever')),
                ('power9', models.BooleanField(blank=True, null=True, verbose_name='Topu havalandırmayı sever')),
                ('power10', models.BooleanField(blank=True, null=True, verbose_name='Uzun top oynamayı sever')),
                ('power11', models.BooleanField(blank=True, null=True, verbose_name='Orta açmayı sever')),
                ('power12', models.BooleanField(blank=True, null=True, verbose_name='Top indirmeyi sever')),
                ('defans1', models.BooleanField(blank=True, null=True, verbose_name='Top çalmaya çalışmaz')),
                ('defans2', models.BooleanField(blank=True, null=True, verbose_name='Top çalmayı sever')),
                ('defans3', models.BooleanField(blank=True, null=True, verbose_name='Sık faul yapar')),
                ('defans4', models.BooleanField(blank=True, null=True, verbose_name='Sık topu defanstan uzaklaştırır')),
                ('defans5', models.BooleanField(blank=True, null=True, verbose_name='Topu yumruklamayı sever')),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Players', verbose_name='Oyuncu')),
            ],
            options={
                'verbose_name': 'Oyuncu oyun stili',
                'verbose_name_plural': 'Oyuncuların oyun stilleri',
            },
        ),
    ]
