# Generated by Django 2.2.2 on 2019-10-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20191016_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='avg_possesion',
            field=models.FloatField(default=None, verbose_name='Topa Sahip Olma'),
        ),
        migrations.AddField(
            model_name='teams',
            name='dribbles_pg',
            field=models.FloatField(default=None, verbose_name='Adam geçme (Maç Başına)'),
        ),
        migrations.AddField(
            model_name='teams',
            name='goal_pg',
            field=models.FloatField(default=None, verbose_name='Gol (Maç Başına)'),
        ),
        migrations.AddField(
            model_name='teams',
            name='pass_accuracy',
            field=models.FloatField(default=None, verbose_name='Pas Yüzdesi'),
        ),
        migrations.AddField(
            model_name='teams',
            name='shoots_pg',
            field=models.FloatField(default=None, verbose_name='Şut (Maç Başına)'),
        ),
        migrations.AddField(
            model_name='teams',
            name='tackles_pg',
            field=models.FloatField(default=None, verbose_name='Top çalma (Maç Başına)'),
        ),
    ]
