# Generated by Django 2.2.2 on 2019-10-28 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20191028_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='league',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Leagues', verbose_name='Lig'),
        ),
    ]
