# Generated by Django 2.2.2 on 2019-10-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20191028_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='avg_possesion',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Topa Sahip Olma'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='dribbles_pg',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Adam geçme (Maç Başına)'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='goal_pg',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Gol (Maç Başına)'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='pass_accuracy',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Pas Yüzdesi'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='shoots_pg',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Şut (Maç Başına)'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='tackles_pg',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Top çalma (Maç Başına)'),
        ),
    ]
