# Generated by Django 2.2.2 on 2019-10-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20191028_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='subs',
        ),
        migrations.AddField(
            model_name='players',
            name='c_red',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kırmızı Kart'),
        ),
        migrations.AddField(
            model_name='players',
            name='c_yellow',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sarı Kart'),
        ),
        migrations.AddField(
            model_name='players',
            name='fouls',
            field=models.IntegerField(blank=True, null=True, verbose_name='Foul'),
        ),
        migrations.AddField(
            model_name='players',
            name='goals_a_pg',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Maç Başına Asist ve Gol'),
        ),
        migrations.AddField(
            model_name='players',
            name='goals_pg',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Maç Başına Gol'),
        ),
        migrations.AddField(
            model_name='players',
            name='mins_pg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Oynadığı Dakika'),
        ),
        migrations.AddField(
            model_name='players',
            name='shot_ot',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kaleyi Bulan Şut'),
        ),
        migrations.AddField(
            model_name='players',
            name='shot_ot_pg',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Maç Başına İsabetli Şut'),
        ),
    ]
