# Generated by Django 2.2.2 on 2019-10-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20191028_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='apps',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Oynadığı Maç Sayısı'),
        ),
        migrations.AlterField(
            model_name='players',
            name='asst',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Asist'),
        ),
        migrations.AlterField(
            model_name='players',
            name='c_red',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kırmızı Kart'),
        ),
        migrations.AlterField(
            model_name='players',
            name='c_yellow',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sarı Kart'),
        ),
        migrations.AlterField(
            model_name='players',
            name='fouls',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Foul'),
        ),
        migrations.AlterField(
            model_name='players',
            name='goals',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Attığı Gol'),
        ),
        migrations.AlterField(
            model_name='players',
            name='goals_a_pg',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Maç Başına Asist ve Gol'),
        ),
        migrations.AlterField(
            model_name='players',
            name='goals_pg',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Maç Başına Gol'),
        ),
        migrations.AlterField(
            model_name='players',
            name='mins_pg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Maç Başına Oynadığı Dakika'),
        ),
        migrations.AlterField(
            model_name='players',
            name='shot_ot',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kaleyi Bulan Şut'),
        ),
        migrations.AlterField(
            model_name='players',
            name='shot_ot_pg',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Maç Başına İsabetli Şut'),
        ),
        migrations.AlterField(
            model_name='players',
            name='starts',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="İlk 11'de Başladığı"),
        ),
    ]
