# Generated by Django 2.2.2 on 2019-11-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20191029_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='aerial_won',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Hava Topu'),
        ),
        migrations.AddField(
            model_name='players',
            name='man_o_match',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Maçın Adamı'),
        ),
        migrations.AddField(
            model_name='players',
            name='pass_success',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Başarılı Pas Yüzdesi'),
        ),
        migrations.AddField(
            model_name='players',
            name='player_rating',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Puanı'),
        ),
        migrations.AddField(
            model_name='teams',
            name='red_card',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Kırmızı Kart'),
        ),
        migrations.AddField(
            model_name='teams',
            name='yellow_card',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Sarı Kart'),
        ),
    ]
