# Generated by Django 2.2.2 on 2019-11-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20191103_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='avg_possesion',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Topa Sahip Olma'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='dribbles_pg',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Adam geçme (Maç Başına)'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='goal_pg',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Gol (Maç Başına)'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='pass_accuracy',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Pas Yüzdesi'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='red_card',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Kırmızı Kart'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='shoots_pg',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Şut (Maç Başına)'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='tackles_pg',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Top çalma (Maç Başına)'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='yellow_card',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Sarı Kart'),
        ),
    ]
