# Generated by Django 2.2.2 on 2019-11-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20191118_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagues',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Lig İkonu'),
        ),
    ]
