# Generated by Django 2.2.2 on 2019-11-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_leagues_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagues',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/leagues/icon', verbose_name='Lig İkonu'),
        ),
    ]
