# Generated by Django 2.2.2 on 2019-11-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20191128_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='emblem',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Takım Logo'),
        ),
    ]
