# Generated by Django 2.2.2 on 2019-11-24 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0026_auto_20191118_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_code', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Lig Kodu')),
                ('hour', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Maç Saati')),
                ('date', models.DateField(blank=True, default='', null=True, verbose_name='Maç Tarihi')),
                ('h_team_logo', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ev Sahibi Takım Logo Konumu')),
                ('a_team_logo', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Deplasman Takım Logo Konumu')),
                ('result', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Sonuç')),
                ('status', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Durum')),
                ('a_team', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_team', to='home.Teams', verbose_name='Deplasman Takım')),
                ('h_team', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_team', to='home.Teams', verbose_name='Ev Sahibi Takım')),
            ],
            options={
                'verbose_name': 'Maç',
                'verbose_name_plural': 'Maçlar',
                'ordering': ['date', 'hour'],
            },
        ),
    ]
