# Generated by Django 2.2.2 on 2019-11-25 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='a_team',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='home.Teams', verbose_name='Deplasman Takım'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='h_team',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='home.Teams', verbose_name='Ev Sahibi Takım'),
        ),
    ]
