# Generated by Django 2.2.2 on 2019-11-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20191125_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='result',
        ),
        migrations.AddField(
            model_name='matches',
            name='result_away',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Deplasman skor'),
        ),
        migrations.AddField(
            model_name='matches',
            name='result_home',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Ev Sahibi skor'),
        ),
    ]
