# Generated by Django 2.2.2 on 2019-12-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_matches_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='match_league',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
